language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"

install: pip install -r dependencies.txt --use-mirrors
script:
  - python setup.py flake8
  - python setup.py test

notifications:
  email:
    - justin.gallardo@rackspace.com
